### ISSUE TITLE
Reestructure roles for more manageable internal control

### ISSUE THREAD

**Issue by Cloudxyz** [blakmetall/pmv#14]
- Los Roles deben de tener permisos por default y estos no pueden ser cambiados por los administradores solo por el Super Admin
- Los permisos de los roles deben ser editables para cada usuario no para cada rol.
- Dando permisos por default a los roles se evita que se pierda congruencia con los roles y que se repitan.
- La estructura de permisos de usuarios deberá ser con checkboxes

**Comment by blakmetall** [comment]
@Cloudxyz 

Sobre esta actividad mejor es hablarles y proponer nuevos roles para asignar zonas específicas; ya que la nueva sección de roles que inicié es muy compleja y considero que la sección actual de permisos y asignación de roles encaja muy bien, solo tenemos que hablarlo mejor; si propon un día lo más pronto posible para ir y hablar de las actividades nuevas que están ingresando y tal vez eliminar otras actividades que no quieren hacer de lleno.

**Comment by Cloudxyz** [comment]
Estas usando algun plugin para esto o checaste alguno? lo comento por que yo en otro proyecto estoy usando este https://spatie.be/docs/laravel-permission/v4/introduction 
es bastante sencillo de usar simplemente creas un permiso como este "php artisan make:permission CreateUser" y luego en el blade o en las rutas puedes poner como lo tenemos solo cambia minimo tipo can('CreateUser' ) y eso solo se veria para los que tienen el permiso, los permisos pueden ser asignados como tenemos ahorita los roles con checkbox y en el transcurso de 2 dias a como lo he visto en el otro proyecto quedaria bien checalo y me dices que pinesas

**Comment by blakmetall** [comment]
Me gustaría hacer lo del plugin, pero en este caso ya tenemos una sección de roles que está muy mezclada con el sistema, es difícil integrarlo como plugin
