### ISSUE TITLE
New Section - report activities and maintenance

### ISSUE THREAD

**Issue by Cloudxyz** [blakmetall/pmv#16]
Se solicito una nueva sección donde se pueda llevar control de cuando se hace alguna actividad o mantenimiento en las propiedades

- Un sistema de property management
- El dueño podrá ver un calendario o listado donde se muestren las actividades que se han hecho en sus propiedades

Se debe recabar información de palmera para saber si ya tienen un calendario rudimentario con los nombres de las actividades que realizan y cada cuanto las realizan

Campos necesarios de la actividad

- Titulo de la actividad / Ambos idiomas
- Fecha de la actividad
- Responsable de la actividad
- Descripción de la actividad
- Estatus de la actividad ("Próximamente", "Realizada")

**Comment by blakmetall** [comment]
"El dueño podrá ver un calendario o listado donde se muestren las actividades que se han hecho en sus propiedades"...

Ya tenemos esta sección en el área administrativa para el registro de servicios donde se muestran los servicios de determinadas propiedades de algún dueño; podemos dar acceso al propietario (creo que ya lo tiene). Si requieren que se haga esa actividad aparte (una especifica para el área de mantenimiento, tendríamos que hablarlo con ellos; ya que es algo que no estaba en el contrato inicial). Propon un día para ir o explicarles que podemos poner más servicios tipo de mantenimiento disponibles en la selección de actividades de servicios disponibles.

- - - - - - - - - 

Si es crear una nueva sección (de mantenimiento específica) hay que ir a la oficina para hablarlo... propon un día

**Comment by Cloudxyz** [comment]
De hecho la propuesta ya la mande debes de tener el correo, te lo acabo de reenviar, les dije tal cual que esta sección tiene un costo extra que se debe definir una vez aceptaba la propuesta, en el correo viene un archivo que tiene la propuesta de la sección, por lo que entendi quieren algo especificamente para eso, quedaron de revisarla y nada mas

**Comment by blakmetall** [comment]
muy bien, te mandé un correo sobre este tema, quedo a la espera de tu revisión para ver que haremos en esta sección
