### ISSUE TITLE
Filter search properties amenities in public home

### ISSUE THREAD

**Issue by Cloudxyz** [blakmetall/pmv#17]
Existe 3 amenidades para filtrar la busqueda de propiedades en la pagina principal de palmeravacations

Se debe hacer una query mixta que filtre tanto por las amenidades como por las fechas

Las amenidades son:

- Pet Friendly
- Adults Only
- -Beach / Water front

**Comment by blakmetall** [comment]
Esta query la haríamos en el área pública cierto?... para dejarla en espera para cuando continuemos en el área pública
