### ISSUE TITLE
Property detail - issue with url when change language

### ISSUE THREAD

**Issue by Cloudxyz** [blakmetall/pmv#18]
Cuando se esta en el detalle de alguna propiedad, a la hora de cambiar de lenguaje arroja un error dado que no encuentra la traducción

La construcción de la url de las propiedades se crea dinámicamente mediante tipo, zona y nombre

Sugerencia:

Agregar un nuevo campo a las propiedades llamado "url" que se construya a la hora de salvar la propiedad y se guarde en español e ingles dinámicamente, así se evita como se esta construyendo cuando se entra al detalle esto puede que evite el error a la hora de cambiar de idioma.

**Comment by blakmetall** [comment]
En que detalle de propiedad; de la zona pública o de la zona administrativa;
Voy a necesitar ayuda para reproducir el error, cuando puedas me compartes screenshots

**Comment by Cloudxyz** [comment]
Es en la zona pública pero actualmente no se puede replicar por que toda la sección publica parece estar oculta ya que causa 404 Not Found por lo pronto comparto pantallas de otra carpeta que tengo


![Captura de pantalla 2021-03-23 174332](https://user-images.githubusercontent.com/8213058/112233131-7291a100-8bff-11eb-9697-422a3076c183.png)
![Captura de pantalla 2021-03-23 174358](https://user-images.githubusercontent.com/8213058/112233137-758c9180-8bff-11eb-823b-05d9078d32e5.png)
![Captura de pantalla 2021-03-23 174415](https://user-images.githubusercontent.com/8213058/112233141-77eeeb80-8bff-11eb-9003-fe8431addaa1.png)
![Captura de pantalla 2021-03-23 174431](https://user-images.githubusercontent.com/8213058/112233149-7b827280-8bff-11eb-9531-2c16a07df8e0.png)

**Comment by blakmetall** [comment]
Esto es del área pública; lo dejamos en espera para cuando esté el área pública lista para trabajar... (ya que quede el sistema del área administrativa).

**Comment by Cloudxyz** [comment]
Estoy de acuerdo todo lo que sea publico ya que este terminado el área administrativa
