### ISSUE TITLE
Merge updates review

### ISSUE THREAD

**Issue by blakmetall** [blakmetall/pmv#36]
Buen día; @Cloudxyz 

- subí los pull requests que tenías listos
- hice el php artisan migrate para que se agregarán los últimos cambios de migraciones (adjunto imagen al fondo)
- corrí el composer dump-autoload y el php artisan optimize para limpiar los archivos
- revisas los cambios en live para que asegures que todo esté bien y si surge algún error o algo lo agregas como issue; estaré al pendiente

**Comment by blakmetall** [comment]
![Screen Shot 2021-04-16 at 4 56 16 AM](https://user-images.githubusercontent.com/80809415/115008212-7916df80-9e70-11eb-8ffc-94483d8e932f.png)

**Comment by blakmetall** [comment]
@Cloudxyz esto ya quedó arriba, imagino que todo quedó bien por que no han habido correos al respecto sobre dificultades de las nuevas integraciones

**Comment by Cloudxyz** [comment]
Si de hecho acabo de checar y esta funcionando los merges que se hicieron ya los errores que ellos comentaron se quitaron, hay que tener cuidado con esto de php artisan migrate por el hecho de que dejamos de usarlos como en septiembre por que habiamos avanzado más que las migraciones entonces ya no las usabamos pero por lo que veo no ocasiono ningun error de tablas ni nada entonces todo correcto

**Comment by blakmetall** [comment]
Gracias por la revisión, si hice lo del migration y tuve cuidado, que bueno que funcionó todo bien; también estoy usando lo del migrate, lo utilicé al remover el campo sleeps del otro issue;

Voy a cerrar este issue
