### ISSUE TITLE
Track system activities with an events or logs table

### ISSUE THREAD

**Issue by blakmetall** [blakmetall/pmv#38]
@Cloudxyz 

propuesta para registrar las actividades del sistema con una tabla de logs (trackear diversas actividades).

con esa tabla registramos quien hizo que cosas del área administrativa y de esa manera pueden revisar actividades de sus empleados con un buscador simple:

propuesta:

-- logs (table)

id
user_id (id del usuario) -- para obtener el nombre del usuario que hizo el evento
event (nombre del evento)
prev_json_data (datos que tenía el registro antes del cambio) los datos relevantes
event_json_data (datos que tiene el registro después del cambio) los datos relevates
created_at

**Comment by Cloudxyz** [comment]
Recomiendo usar este plugin yo lo uso en otros sistemas y funciona muy bien te trackea todo lo que tu le indiques

http://www.laravel-auditing.com/

es bastante sencillo de usar y por el momento me ha funcionado bien

**Comment by blakmetall** [comment]
Está bien, yo voy a realizar esta actividad; reviso el plugin y a ver que tal, si no me funciona lo haré con la tabla de logs que preparé
